// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeIHXgR2glQXLQDz06M4YY_9aSzSEKxoY',
    appId: '1:701388790020:web:8aac6074e4eab604b21851',
    messagingSenderId: '701388790020',
    projectId: 'authentication-1e8e8',
    authDomain: 'authentication-1e8e8.firebaseapp.com',
    storageBucket: 'authentication-1e8e8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUtZko4rn2k3sBXLlH7q6GlTRXN4pYo10',
    appId: '1:701388790020:android:c58c8d7ae2de8232b21851',
    messagingSenderId: '701388790020',
    projectId: 'authentication-1e8e8',
    storageBucket: 'authentication-1e8e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC6YuajelACMUO_tzkHa8ykHFNUxSz6yc',
    appId: '1:701388790020:ios:0c482d5e6bfb5fb0b21851',
    messagingSenderId: '701388790020',
    projectId: 'authentication-1e8e8',
    storageBucket: 'authentication-1e8e8.appspot.com',
    iosClientId: '701388790020-qe66dc4ksnq3ifjvmckksnc34ko6p67r.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC6YuajelACMUO_tzkHa8ykHFNUxSz6yc',
    appId: '1:701388790020:ios:0c482d5e6bfb5fb0b21851',
    messagingSenderId: '701388790020',
    projectId: 'authentication-1e8e8',
    storageBucket: 'authentication-1e8e8.appspot.com',
    iosClientId: '701388790020-qe66dc4ksnq3ifjvmckksnc34ko6p67r.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentication',
  );
}
